#!/usr/bin/env python3
"""Summarize cc=10 targeted-label-flip telemetry."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--detail-csv",
        type=Path,
        default=Path("PFLlibMonza/system/cc_detail_results_10.csv"),
        help="cc_detail_results_10.csv generated by MONZA.",
    )
    parser.add_argument(
        "--tail-rounds",
        type=int,
        default=30,
        help="Number of final rounds used for the summary.",
    )
    return parser.parse_args()


def latest_run(df: pd.DataFrame, min_rounds: int) -> pd.DataFrame:
    if "RunID" in df.columns:
        run_ids = list(df["RunID"].drop_duplicates())
        for run_id in reversed(run_ids):
            run = df[df["RunID"] == run_id].copy()
            if run["Round"].astype(int).nunique() >= min_rounds:
                return run
        return df[df["RunID"] == run_ids[-1]].copy()
    rounds = df["Round"].astype(int)
    starts = df.index[rounds < rounds.shift(fill_value=rounds.iloc[0])].tolist()
    start = starts[-1] if starts else 0
    return df.loc[start:].copy()


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.detail_csv)
    if df.empty:
        raise SystemExit(f"{args.detail_csv} vazio.")
    df = latest_run(df, args.tail_rounds)
    tail_round_values = sorted(df["Round"].astype(int).unique())[-args.tail_rounds :]
    tail = df[df["Round"].isin(tail_round_values)].copy()

    score_cols = [
        "MLPScore",
        "BERTScore",
        "TargetLFScore",
        "TargetLFMarginDelta",
        "TargetLFLossDelta",
        "TargetLFTargetProbDelta",
        "TargetLFHeadScore",
        "TargetLFFinalDelta",
    ]
    rows = []
    for attack_type, group in tail.groupby("AttackType", sort=True):
        total = len(group)
        removed = int(group["Removed"].sum())
        target_hits = int(group.get("TargetLFHit", pd.Series(dtype=int)).sum())
        score_outliers = int(group.get("TargetLFScoreOutlier", pd.Series(dtype=int)).sum())
        behavior_allowed = int(group.get("TargetLFBehaviorAllowed", pd.Series(dtype=int)).sum())
        capped = int(group.get("TargetLFCapped", pd.Series(dtype=int)).sum())
        row = {
            "AttackType": attack_type,
            "Total": total,
            "Removed": removed,
            "Rate": removed / total if total else 0.0,
            "Metric": "FPR" if attack_type == "benign" else "recall",
            "TargetLFHitRate": target_hits / total if total else 0.0,
            "TargetLFScoreOutlierRate": score_outliers / total if total else 0.0,
            "TargetLFBehaviorAllowedRate": behavior_allowed / total if total else 0.0,
            "TargetLFCappedRate": capped / total if total else 0.0,
        }
        for col in score_cols:
            if col in group:
                row[f"{col}_mean"] = float(group[col].mean())
                row[f"{col}_p95"] = float(group[col].quantile(0.95))
        rows.append(row)

    summary = pd.DataFrame(rows)
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
